### ISSUE TITLE
Notifications with unicode characters [edit of original OP title "Missing instructions / files to compile"]

### ISSUE THREAD

**Issue by waptaff** [halnovemila/Notify4Scripts#1]
Notify4Scripts works in principle for me, but it appears that unicode characters get mangled somewhere in the chain, garbling strings in commands such as:

```
am startservice \
  -e str_title "" \
  -e str_content "Noël is xmas in french" \
  -n com.hal9k.notify4scripts/.NotifyServiceCV
```

I'd like to try and debug it, but I cannot compile Notify4Scripts myself, as there are missing files such as `AndroidManifest.xml`, possibly `build.xml` and others.

Thanks for looking at it!

**Comment by halnovemila** [comment]
Hi waptaff, the unicode issue has little to do with Notify4Scripts app, it's rather related to the more general subject of how to handle unicode characters in bash scripts.

I never been into this subject but I did some Google searches today and a number of tests till I've been successful on properly build the notification as per the example you provided.

I've been inspired by the comprehensive answer wrote by Adam Zalcman in here:
http://stackoverflow.com/questions/8334266/how-to-make-special-characters-in-a-bash-script-for-conky

I found the UTF-8 codes here:
http://www.charbase.com/00eb-unicode-latin-small-letter-e-with-diaeresis

Then I executed the following commands on a terminal 
```
UCC=$'\xc3\xab'
am startservice \
  -e str_title "Unicode test" \
  -e str_content "No${UCC}l is xmas in french" \
  -n com.hal9k.notify4scripts/.NotifyServiceCV
```
Please note that the brackets { } around the variable name UCC are required in case the variable name isn't followed by a space.
I also tried other escaped codes and I found out that Java Escape '\u00eb' worked as well as UTF-8 '\xc3\xab\'

[![Screenshot_2017-04-22-16-13-02.png](https://s19.postimg.org/pfbmxwnib/Screenshot_2017-04-22-16-13-02.png)](https://postimg.org/image/6zr60i9dr/)

**Comment by waptaff** [comment]
Thanks for the resolution and examples! That rocks!

**Comment by halnovemila** [comment]
You are welcome :)
