### ISSUE TITLE
notify4scripts usable on non-rootet devices?

### ISSUE THREAD

**Issue by nephilim1973** [halnovemila/Notify4Scripts#2]
Hi,
is it possible to use this app on non-rooted devices ?
If yes, could you explain a short szenario to display a simple text via adb on the device ?

Thanks a lot and cheers.

PS: I have read the short description on xda-developers:
https://forum.xda-developers.com/showpost.php?p=69859668&postcount=18

"the Android system needs to be rooted first"

Would it be possible to create a version for non-rootet devices ??

**Comment by halnovemila** [comment]
Hi Nephilim,
I wrote a Wiki years ago which is available here in GitHub together with the code of my tiny project.
You may have not seen the Wiki  tab on GitHub if you have watched the mobile version of the website. 
Anyway, this is the direct link to the Wiki 
https://github.com/halnovemila/Notify4Scripts/wiki

In theory the app may work with basic functions with user privileges (just only for displaying a notification  but no actions  associated to the notification itself) but I'm not sure, also I can't try it now myself on a non rooted device as I don't have any handy available. 
The best is you try it on your target system. The following is the minimum command line for testing purposes (the --user  parameter can be optional too on pre KitKat Android versions)

am startservice --user 0 -n com.hal9k.notify4scripts/.NotifyServiceCV

Just open a console and execute that line and see what's the outcome. 
On my rooted phone if I execute that line from a user prompt ($) I get the following message displayed 

Error: Requires permission not exported from uid 10220

Given the simple task performed by my tiny app (it basically reads the parameters from the invoking command line and pass them to the notification builder API) I think it's very likely possible to make a  version that can work on non rooted devices; maybe what's needed it's just a  properly made AndroidManifest.xml file.
But personally I'm not in conditions to make it.

Regards. 
Alex

**Comment by mirfatif** [comment]
@halnovemila Thanks for this wonderful app. I know nothing about coding but in this issue I think you need to [export](https://developer.android.com/guide/topics/manifest/service-element.html#exported) services in manifest. Something like:
```
<service android:name=".NotifyService" android:exported="true"/>
```
Not sure if any further actions needed. Please consider as it would be a useful addition.

**Comment by halnovemila** [comment]
Hi Mirfatif!
Thanks for your suggestion and your appreciation and interest on my little piece of software that I feel shy to call it app ;-)
I wonder if you make any use of it and how you found it.
Mind to share with me? 

All good things, 
Alex

**Comment by mirfatif** [comment]
@halnovemila I found it on xda. We talked [here](https://forum.xda-developers.com/showpost.php?p=77736031&postcount=19) previously. I have a minimal Linux environment on my phone to run `sshd`, `dnscrypt-proxy`, `crond`, `rclone` etc. So the only way ro get notified of events, particularly failures, is your app. I use custom actions to turn `adbd`, location etc. off (if left turned on for some time) by tapping the notification. Also `rclone` asks me to allow sync files larger than 100MBs through a notification. I get notified when internet/WiFi goes up/down. And some other similar uses. :-)

And I send notifications either from shell scripts or `init`'s `.rc` files.

**Comment by halnovemila** [comment]
Wow! Cool! 
Actually I had the feeling to have already met your username somewhere in the past... but it's past already more than one and an half year... haha... no wonder that I can't remember. 
Anyway, congratulations for the creative ways you used my little "app" and thanks again for coming back here with a suggestion that can eventually make it possible to have notify4scripts usable on non-rooted devices. 
:-)

P.S. How about to make a thread on XDA where you share all or some of the useful uses you conceived of custom notifications made by shell scripts? ;-)
