### ISSUE TITLE
Android 8.1 rooted.

### ISSUE THREAD

**Issue by ghost** [halnovemila/Notify4Scripts#3]
I do not know if this is for android 8.1 or if I'm doing something wrong but when app lunches and the "read launcher DB" his taped on I get a "Sorry, can't read launcher DB. Can't find any authority provider that declares this permission" "com.android.launcher.permission.READ_SETTINGS"
I am rooted with magisk manager. 
What I'm trying to do is have my Raspberry pi 3 send a adb/ssh push notification when a condition is triggered (IE. High temp) I can not find anything on line regarding how to go about doing this and was hoping that this .apk was the solution. If I'm wrong then disregard this and close it.

**Comment by halnovemila** [comment]
I can't say for sure if my old little app can still work on such new version of Android, but I can say for sure that you can totally and safely ignore the graphic interface of the app and the "Read launcher DB" function. 
That was designed to work on Samsung Galaxy Y launcher, to provide a quick way to read the intents and parameters for each app with an icon on the Home screen. 
Notify4Script works only by invoking it via command line commands and all it needs is a properly formatted command line. 
Please read the Wiki page for usage and examples. 
Hope this helps. 

Let me know if you'll be successful 😊
