### ISSUE TITLE
Starting service: Intent {cmp=com.hal9k.notify4scripts/.NotifyServiceCV (has extras) }

### ISSUE THREAD

**Issue by ghost** [halnovemila/Notify4Scripts#4]
Hi, halnovemila! I have a problem:
am startservice -n com.hal9k.notify4scripts/.NotifyServiceCV -e str_exec "touch File.txt" -e int_id 6 -e str_title "Make a file" -e hex_tcolor "000000" -e float_csize 16 -e str_content "Create a new empty file in /mnt/sdcard with name File.txt"
does not work. It writes:
Starting service: Intent {cmp=com.hal9k.notify4scripts/.NotifyServiceCV (has extras) }

I have tried --es --esn --ei, but no success.
My android version 2.3.6. Appreciate for any help!

**Comment by halnovemila** [comment]
Hi, 
it seems to me that the extra parameter str_exec isn't complete. 
You need to provide the path to the executable which will execute the command you want to be executed. 
In your case "touchFile.txt" isn't an executable so trying to "run" it will cause an error. 
Have you read the available Wiki that I wrote with many examples and descriptions?
